### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Valerianych** [maxivz/interactivetoolsblender#25] opened 2024-07-19 15:54 UTC
It gives an error and "No module named 'mesh_f2' does not work

**Comment by Jordan-64** [comment] 2024-07-21 10:17
I haven't tested it extensively but if you copy the file [https://raw.githubusercontent.com/blender/blender-addons/main/mesh_f2.py](url) into "Blender/4.2/scripts/addons" it seems to work.

**Comment by danilkaden** [comment] 2024-07-21 18:37
please. can you send a file again. couse when i try to come in links i have a "No results matched your search."

**Comment by Jordan-64** [comment] 2024-07-22 09:06
> please. can you send a file again. couse when i try to come in links i have a "No results matched your search." or give me advice when i can find this file

url is fixed, try again.

**Comment by ariel3diaz** [comment] 2024-07-23 03:16
Tried this new version and got to some issues. 

Super Smart Create, when used to connect vertices ('Connect Vertex Path' which i think is an F2 tool) works fine. However, when you selct vertices to create new faces (F2's New Edge/Face From Vertices) the tool doesn't work. In the example below, I'd expect for new faces to appear where the blue lines are after consecutive presses.

![image](https://github.com/user-attachments/assets/79b033b6-9b3b-4fc8-9a83-50697fe6f0b3)

Also, for the addon to work and not give me the missing f2 error, I have to copy f2 to my 'bender-4.2.0...\portable\scripts\addons folder. f2 now lives in 'blender-4.2.0-windows-x64\portable\extensions' so the interactive tools addon can't find it.

**Comment by Jordan-64** [comment] 2024-07-23 15:56
I'm not sure if i understand but in your example above, when you select the two vertices and press "F" repeatedly then it creates new faces were the blue lines are. Also i have no problems with the installation of the addon. I have enabled the F2 extension and than i dragged the zip file of the addon in the blender window and it works.

**Comment by Ollymoss** [comment] 2024-07-23 17:31
On MacOS, I could only get the new fork to activate by moving the F2 addon from the new "extensions" folder that blender 4.2 automatically creates into the old "addons" folder. After that, the addon seems to work as expected.

**Comment by ariel3diaz** [comment] 2024-07-23 18:25
Reinstalled it and now  'super smart create' works as intended. However, like Ollymoss stated above I have to move the F2 addon from the extensions dir and into my portable/addons folder, next to interactive tools. Maybe this is a bug that only affects portable installs (so maybe if your configs live inside of Appdata this isn't an issue?).

**Comment by Jordan-64** [comment] 2024-07-23 18:31
> On MacOS, I could only get the new fork to activate by moving the F2 addon from the new "extensions" folder that blender 4.2 automatically creates into the old "addons" folder. After that, the addon seems to work as expected.

I think the Forked addon has some Hard coded Windows paths.

**Comment by Jordan-64** [comment] 2024-07-23 18:35
> Reinstalled it and now 'super smart create' works as intended. However, like Ollymoss stated above I have to move the F2 addon from the extensions dir and into my portable/addons folder, next to interactive tools. Maybe this is a bug that only affects portable installs (so maybe if your configs live inside of Appdata this isn't an issue?).

Are your blender extensions in "C:\Users\YOUR_WINDOWS_USER_PATH\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org"?

I also use the Portable version and my Extensions are in that path.

**Comment by Jordan-64** [comment] 2024-07-25 06:13
> > > Reinstalled it and now 'super smart create' works as intended. However, like Ollymoss stated above I have to move the F2 addon from the extensions dir and into my portable/addons folder, next to interactive tools. Maybe this is a bug that only affects portable installs (so maybe if your configs live inside of Appdata this isn't an issue?).
> > 
> > 
> > Are your blender extensions in "C:\Users\YOUR_WINDOWS_USER_PATH\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org"?
> > I also use the Portable version and my Extensions are in that path.
> 
> No, I don't even have a 'Blender Foundation' folder inside of AppData/Roaming. My extensions live in: blender-4.2.0-windows-x64\portable\extensions\blender_org
> 
> The Appdata path is created automatically the first time you run a new blender install if you don't already have a 'blender-4.2.0-windows-x64\portable' that you've created manually. In my case I created this 'portable' dir so my extensions go there by default instead.

There is a hard coded path in the new addon

extensions_path = home_directory + f'\\AppData\\Roaming\\Blender Foundation\\Blender\\{version_string}\\extensions\\blender_org'

That's maybe the problem

**Comment by maxivz** [comment] 2024-08-02 16:06
I am merging changes right now that should start to fix some of these issues. Please let me know if this isn't fixed
Ill keep looking at these issues during the next days, but it might take a while

**Comment by maxivz** [comment] 2024-08-11 06:10
Ill close this issue as it has now been fixed in the new release, thanks everybody for reporting and contributing!

**Closed by maxivz** 2024-08-11 06:10 UTC
